### ISSUE TITLE
bug if add many cron at the same time

### ISSUE THREAD

**Issue by jilieryuyi** [robfig/cron#151] opened 2018-08-22 00:31 UTC
08:28:31.667 [trace] entity.go:106 | ##########################1, 1=>[1681,ls /] start run##########################
08:28:31.667 [trace] entity.go:106 | ##########################2, 2=>[1681,ls /] start run##########################
08:28:31.667 [trace] entity.go:106 | ##########################3, 3=>[1681,ls /] start run##########################
08:28:31.674 [trace] entity.go:106 | ##########################4, 4=>[1681,ls /] start run##########################
08:28:31.675 [trace] entity.go:106 | ##########################5, 5=>[1681,ls /] start run##########################
08:28:31.688 [trace] entity.go:106 | ##########################6, 6=>[1681,ls /] start run##########################
08:28:31.701 [trace] entity.go:114 | ##########################1, 1=>[1681,ls /] run end##########################
08:28:31.701 [trace] entity.go:114 | ##########################2, 2=>[1681,ls /] run end##########################
08:28:31.703 [trace] entity.go:114 | ##########################4, 4=>[1681,ls /] run end##########################
08:28:31.710 [trace] entity.go:114 | ##########################6, 6=>[1681,ls /] run end##########################
08:28:31.721 [trace] entity.go:114 | ##########################3, 3=>[1681,ls /] run end##########################

cron set:
data := make(url.Values)
	data.Add("cron_set", "*/1 * * * * *")
	data.Add("command", "ls /")
	data.Add("remark", "")
	data.Add("stop", "0")
	data.Add("start_time", "0")
	data.Add("end_time", "0")
	data.Add("is_mutex", "0")

try to add 4 at the same time, 1681 cron is run many times at one second~

**Comment by jilieryuyi** [comment] 2018-08-22 13:13
effective.Sub=> -15.380148951s
now=> 2018-08-22 21:11:16.380775804 +0800 CST m=+42.468457643
now=> 2018-08-22 21:11:16.380775804 +0800 CST m=+42.468457643
effective.Sub=> -14.380775804s
now=> 2018-08-22 21:11:16.381923528 +0800 CST m=+42.469605338
21:11:16.379 [info] db.go:122 | Add success, sql=[INSERT INTO `cron`(`cron_set`, `command`, `stop`, `remark`, `start_time`, `end_time`, `is_mutex`) VALUES ("*/1 * * * * *","ls /","0","","0","0","0")]
now=> 2018-08-22 21:11:16.381923528 +0800 CST m=+42.469605338
effective.Sub=> -13.381923528s

effective.Sub  is < 0

**Comment by zhiqiang-bianjie** [comment] 2018-09-21 06:07
I also encountered this problem.

**Comment by nuczzz** [comment] 2018-12-03 01:44
> I also encountered this problem.

So am I, have you solved the problem yet?

**Comment by lifb** [comment] 2019-03-08 07:16
I also encountered this problem, and have both of you solved the problem yet ?
@zhiqiang-bianjie @nuczzz

**Comment by robfig** [comment] 2019-05-03 01:16
Sorry, can someone provide a program I can run to see the incorrect result? This works for me:

```
package main

import (
	"fmt"

	"github.com/robfig/cron"
)

func main() {
	c := cron.New()
	c.AddFunc("*/1 * * * * *", func() { fmt.Println("A") })
	c.AddFunc("*/1 * * * * *", func() { fmt.Println("B") })
	c.AddFunc("*/1 * * * * *", func() { fmt.Println("C") })
	c.AddFunc("*/1 * * * * *", func() { fmt.Println("D") })
	c.Run()
}
```

**Comment by holyzhuo** [comment] 2019-06-05 02:29
i have same problem

**Comment by jilieryuyi** [comment] 2019-06-06 01:53
fix by code:

case newEntry := <-c.add:
			c.entries = append(c.entries, newEntry)
			//newEntry.Next = newEntry.Schedule.Next(now)
			//如上存在bug，修正如下
			newEntry.Next = newEntry.Schedule.Next(time.Now().Local())
			fmt.Fprintf(os.Stderr, "newEntry=%+v\r\n", *newEntry)

**Comment by robfig** [comment] 2019-06-16 12:50
Can anyone confirm that this still happens on the v3 branch? It includes all of the fixes from both v1 and v2.

**Comment by robfig** [comment] 2019-07-11 17:49
I'm going to close this as I'm cleaning up issues. Feel free to reopen if you can reproduce with v3 or if you have a program that demonstrates the incorrect result. Otherwise I can not reproduce. Thanks

**Closed by robfig** 2019-07-11 17:49 UTC

**Comment by monikanaico-hub** [comment] 2021-11-01 06:56
@robfig  first time I used v1 and added a cron job and give build, then I started getting notifications, then I changed the time and give build then I started getting 2 notification.. Then I changed to V3.. .But I am getting 2 notification. How can I delete ALL the existing cron job?
