### ISSUE TITLE
update cron schedule for job

### ISSUE THREAD

**Issue by pradykaushik** [robfig/cron#273] opened 2019-12-31 07:11 UTC
It would be beneficial to provision for updating the schedule for a job. Currently, the only way to do this (correct me if I am wrong) is to stop the job and recreate it with the new schedule. The following things need to be considered.
1. We should be able to identify a job using a name/id of sorts. This can be done using the [ID returned by cron.Schedule()](https://github.com/robfig/cron/blob/b7cc47d857a82296e8133b0706adb5754f5ab163/cron.go#L158).
2. If updating the schedule, [Next](https://github.com/robfig/cron/blob/b7cc47d857a82296e8133b0706adb5754f5ab163/cron.go#L60) should also be updated to make sure that the new schedule is adhered to starting from the next execution of the job.

@robfig please let me know your thoughts on this. I would be happy to work on it and submit a PR.

**Comment by robfig** [comment] 2020-01-04 01:15
Thanks for your interest. I agree that adding an `Cron.UpdateSchedule(EntryId, Schedule)` method would be straightforward to implement and potentially useful. I would accept it, assuming it comes with unit tests. 
Thanks

**Comment by robfig** [comment] 2020-01-04 01:32
(Closing as dupe of #182)

**Closed by robfig** 2020-01-04 01:32 UTC
