### ISSUE TITLE
Call twice because of run time not accurate

### ISSUE THREAD

**Issue by mnhkahn** [robfig/cron#72] opened 2016-09-13 01:31 UTC
I have a crontab job run every 10 minutes. I found that when it call at `2016/09/13 08:49:59`, it will call again at `2016/09/13 08:50:00`. It will then call twice.

**Comment by robfig** [comment] 2016-09-14 03:01
Do you have a code snippet so I can try to reproduce?

**Comment by aobco** [comment] 2016-10-28 07:08
@mnhkahn , I fixed it like this:  [cron.go:186]  now = now.In(c.location).Round(time.Second)

**Comment by robfig** [comment] 2019-06-15 02:27
I believe that this is a dupe of #59. It should be fixed on v3.

**Closed by robfig** 2019-06-15 02:27 UTC
